### ISSUE TITLE
Add YAML syntax highlighting

### ISSUE THREAD

**Issue by ebkalderon** [azerupi/mdBook#103]
It seems that with isagalaev/highlight.js#119, the Highlight.js library now supports syntax highlighting for YAML. However, when I annotate some YAML with ````yaml`, no syntax highlighting appears.

**Comment by ebkalderon** [comment]
@azerupi Could you perhaps explain why this is happening? Does mdBook use an older version of Highlight.js for syntax highlighting?

**Comment by azerupi** [comment]
Yes, I haven't updates highlight.js since August, I think.

I am rewriting mdBook to have a sort of plugin api and will extract the
code that manages the syntax highlighting into a more isolated plugin. When
that is done I will probably switch to a dependency manager like Bower to
update dependencies on a regular basis.

Also I have disabled auto-detect, because in my experience it doesn't
always work like it is supposed too. When it's a plugin I will probably add
an option in the config file to indicate a default language.

But.. at the moment I am on vacation ;)

**Comment by ebkalderon** [comment]
@azerupi Sounds good. Until then, please relax and enjoy your vacation!

**Comment by Luthaf** [comment]
YAML support is not activated by default in highlight.js code. As a temporary workaround, you could [download highlight.js](https://highlightjs.org/download/) (Custom package section) from there website, activating all the languages you need, and then putting the file in `src/theme/highlight.js`.

**Comment by azerupi** [comment]
Yes, @ebkalderon you can do like @Luthaf suggests until I update the in tree version. You can read more about the process of overriding default theme files in [the documentation](http://azerupi.github.io/mdBook/format/theme/theme.html).

If you do, let me know if it fixes the issue
