### ISSUE TITLE
Readiness to be a dependency for rustc?

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#105]
In https://github.com/rust-lang/rust/issues/31590#issuecomment-183464245, we're discussing how to generate the longform docs in the new Cargo-based build system.

Is mdBook up for this yet? I don't have any particular reason why it would _not_, but figured I'd ask first. :smile:

**Comment by azerupi** [comment]
I don't have a problem with that, but I would personally recommend to wait until I release 0.1.0

I want to move to a TOML based configuration file, add multilingual support and move optional features to "plugins" that can be enabled  through the configuration file. So it will be a "breaking" release. 

I assume that being a rustc dependency adds some constraints to breaking changes?
Is there a way to specify specific versions for binaries with `cargo install`? If there is, it's less of a problem, because you are not bound to the latest release I pushed.

**Comment by steveklabnik** [comment]
> I assume that being a rustc dependency adds some constraints to breaking changes?

Not currently. Almost nothing in the ecosystem is 1.0 in general, so all of the dependencies have breaking changes and get updated whenever someone wants to update them, and then they have to fix it as well.

> Is there a way to specify specific versions for binaries with cargo install?

Lots:

```
Specifying what crate to install:
    --vers VERS               Specify a version to install from crates.io
    --git URL                 Git URL to install the specified crate from
    --branch BRANCH           Branch to use when installing from git
    --tag TAG                 Tag to use when installing from git
    --rev SHA                 Specific commit to use when installing from git
    --path PATH               Filesystem path to local crate to install
```

> because you are not bound to the latest release I pushed.

Ah, well given `Cargo.lock`, it shouldn't just update itself automatically anyway; we'd be picking a version and upgrading when we plan to like usual.

**Comment by azerupi** [comment]
In that case, I don't have any objection.
If you think it is ready enough, that is all that matters :)

**Comment by steveklabnik** [comment]
Great! 

It's not totally clear when the Cargo-based system will actually land, so it might be post-1.0 anyway. Just wanted to hear your thoughts. :+1:
