### ISSUE TITLE
Curious error in Travis build

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#129]
@japaric Sorry to ping you again, but there seems to be a curious bug causing the automated builds to fail.

[Travis says](https://travis-ci.org/azerupi/mdBook/jobs/122890491):
```
error: the crate `std` has been compiled with rustc 1.9.0-beta.1 (37a2869af 2016-04-12), which is incompatible with this version of rustc [E0514]
```

It fails only for a couple of targets. Have you an idea of what is going on?

**Comment by japaric** [comment]
> @japaric Sorry to ping you again, but there seems to be a curious bug causing the automated builds to fail.

It's OK to ping in cases like this :smile:

> Have you an idea of what is going on?

Yeah, we recently got a new beta release. We use multirust to install the beta rustc, but fetch the std crates from static.rust-lang.org. It appears we are using the wrong URL for that (hence we get beta.1 instead of beta.2) but it's best to just use multirust to install the std crates. I'll send a patch in a bit.

**Comment by azerupi** [comment]
Great! Thanks for your help :)

**Comment by japaric** [comment]
Oh, right. This Travis setup is an "old" version of rust-everywhere and it's using Travis' built-in Rust support instead of multirust or rustup. Hmm, it would be easier for me to move the setup to use rustup so I guess I'll do that instead.

**Comment by azerupi** [comment]
That's totally fine with me! :wink:
