### ISSUE TITLE
Links looks ugly when javascript is disabled

### ISSUE THREAD

**Issue by onur** [azerupi/mdBook#144]
Javascript is disabled on my browser and links in a page generated by mdBook don't have any default style and they look so ugly. Example book without javascript:

[![book](https://i.imgur.com/0KPnbxal.png)](https://i.imgur.com/0KPnbxa.png)

This is not an issue on gitbook, and I believe it would be much better if mdBook uses `light` theme by default, and without any javascript.

And thanks for this awesome project!

**Comment by azerupi** [comment]
Indeed, I noticed that part of the style is not applied when JS is disabled. I haven't had the time yet to really look into it, but I have an idea what might be causing this.

It's probably just the class of the theme that isn't set when JS is disabled, and since all the theme styling is applied only on that class, part of it is not applied. The fix is probably as easy as setting a default class in the handlebars template.

I will look into it when my exams are over if no one else fixes it until then :wink: 

>And thanks for this awesome project!

:blush: Thanks for the kind words
