### ISSUE TITLE
Add an empty, but included last, `custom.css` file

### ISSUE THREAD

**Issue by carols10cents** [azerupi/mdBook#178]
I'd like to be able to add just a few little custom style rules, but I don't want to maintain my own version of book.css or highlight.css that might diverge from the mdbook provided styles.

What do you think about mdbook always including, or trying to include if it exists, a file named `custom.css` or similar, that mdbook would intentionally never add anything to?

This file would need to be included last, so that the rules in `custom.css` would be able to override rules in `book.css` or `highlight.css`.

I'd be happy to work on a PR for this, but wanted to see if this was something you'd be interested in first.

**Comment by azerupi** [comment]
Definitely!
I planned to add this when the change to TOML configuration file and the Renderer abstraction was done. I envisioned something like below. (Not the final design, needs some thought)

```toml
[outputs.html]
path = "book/"
css = ["custom.css"]
js = ["custom.js"]
```

However, since things have been moving really slowly. I would definitely be open to a temporary solution. I don't want to block everything on a rewrite that could still take forever to get done :confused:

**Comment by gambhiro** [comment]
I added behaviour for this in [multilang](https://github.com/gambhiro/mdBook/tree/multilang) for #200.

It checks a few locations for a `custom.css` and if found, it adds a `<link>` to it after the template's css in the `<head>`.

It looks in the following paths, the first wins:

- assets/css/custom.css
- assets/stylesheets/custom.css
- assets/custom.css

@carols10cents is this what you had in mind?
