### ISSUE TITLE
Use serde instead of rustc-serialize ?

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#18]
I have heard good things about serde. At the moment I use rustc-serialize, should I use serde instead?

What are the differences?

**Comment by kbknapp** [comment]
`serde` is super nice when used in the nightly branch because you can simply mark your structs as `#[derive(Serialize)]` or `#[derive(Deserialize)]` and then encode/decode them to any format supported by serde (I used JSON, but I hear YAML is being worked on too). It worked perfectly!

The downside is you're limited to the nightly branch. `serde` *can* be used on stable, but you end up implementing those traits yourself (which isn't too hard, but it is work). 

Beyond that, I don't have a lot of knowledge about the differences :\

**Comment by azerupi** [comment]
Ok thanks for the clarification! 
I will probably wait until all the features are in stable then, and focus on the other things in the meantime.

**Comment by gambhiro** [comment]
Just for reference, this is waiting for rust-lang/rust/issues/29597 and rust-lang/rust/issues/29644 to land in stable.

**Comment by azerupi** [comment]
I think it would be OK to make the jump now. Serde is becoming the defacto serialiser / deserialiser even though some ergonomic features are only available on nightly.

I think there are 2 ways we can make it work:

- Using [serde_codegen](https://github.com/serde-rs/serde#using-serde-with-stable-rust-and-serde_codegen)
- Manual implementation

Code gen is obviously more convenient but requires some extra work in the build script. Which is not a big deal.

**Comment by gambhiro** [comment]
I followed the serde readme and made an experiment in [this branch](https://github.com/gambhiro/mdBook/tree/serde-with-codegen), refactoring only `bookconfig.rs`.

Although it works, the build time has become quite long, 1.5 mins instead of 9 secs.

With codegen:

```
cargo build  86.78s user 0.57s system 99% cpu 1:27.37 total
```

while before:

```
cargo build  8.93s user 0.37s system 99% cpu 9.327 total
```

I didn't PR because I think it's not worth the long feedback time while working. The feature tickets are apparently being worked on, I suggest waiting until they arrive in the stable release.

**Comment by azerupi** [comment]
That is a reasonable choice, thanks for looking into it :)

**Comment by dtolnay** [comment]
@gambhiro that doesn't seem like a fair comparison because you are not including any of the other dependencies.

On my computer a build following `cargo clean` takes 68 seconds without serde_codegen and 115 seconds with serde_codegen, but subsequent builds take 9 seconds either way. When iterating you only care about the 9 second time which is the same for both.

**Comment by gambhiro** [comment]
@dtolnay Thanks for explaining. I'm quite new to the rust build tools.
