### ISSUE TITLE
Integrate ACE for editing

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#247]
This is the last thing needed to get Rust By Example over to mdbook.

I did some work on this today, and it seems like ACE clashes with something else we're doing; the divs just don't show up.

**Comment by azerupi** [comment]
If ACE is integrated, it should be optional with a key in the config. It's too large of a dependency to impose on all users.

**Comment by projektir** [comment]
I've been poking at trying to add Ace to playpens for a bit. Since this is about adding features to mdBook, it would help knowing what mdBook's overall goals are, and this is my first time looking at this repo.

@azerupi does mdBook have interest in implementing editing functionality in the general case? I've seen what appears to be a dormant flag `editable` in the code. If mdBook does not want to use Ace for this, what are the other options?

> It's too large of a dependency to impose on all users.

mdBook currently has highlight.js as a dependency, which is not too light (although it can be reduced to basically nothing if a version for just Rust is grabbed). Ace is heavier, but would make highlight.js unnecessary. Right now, Ace will not work inside playpens because highlight.js seems to grab events on code blocks.

**Comment by azerupi** [comment]
> does mdBook have interest in implementing editing functionality in the general case?

As an opt-in feature, yes. It is not something I want to force on all users if they don't need it.

> mdBook currently has highlight.js as a dependency, which is not too light

Indeed, in the long run I was planning to take a look at [syntect](https://github.com/trishume/syntect) as an alternative in order to move syntax highlighting to the book generation phase. But that is not for right now.
