### ISSUE TITLE
Run button is displayed twice on runnable rust files

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#251]
![image](https://cloud.githubusercontent.com/assets/7647338/25061907/b3e5c1e8-21c0-11e7-811d-6df57c33f8cf.png)

**Comment by steveklabnik** [comment]
hmmmmmmmmmmmmm

**Comment by crazymerlyn** [comment]
This is happening because of nested playpens.

Runnable rust files are rendered with a playpen block [here](https://github.com/azerupi/mdBook/blob/master/src/renderer/html_handlebars/helpers/playpen.rs#L38,L39).

But all rust code is wrapped with another playpen block [here](https://github.com/azerupi/mdBook/blob/master/src/renderer/html_handlebars/hbs_renderer.rs#L307,L332).

[This query](https://github.com/azerupi/mdBook/blob/master/src/theme/book.js#L185,L198) interprets them as two blocks and adds the run button twice.

Replacing `<pre class="playpen">` with `<pre>` in the playpen helper fixes the problem.

**Comment by steveklabnik** [comment]
Ah ha!
