### ISSUE TITLE
regression on default theme directory handling

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#313]
Hi,

Since  https://github.com/azerupi/mdBook/pull/287
The contents of "theme" directory is no longer taken into account by default (in case no book.toml config is present like in rust-cookbook).

Is this expected (code does not handle the "default case")?

**Comment by budziq** [comment]
Otherwise maybe lets just drop the "defaults" and require book.toml to override the "theme".

**Comment by azerupi** [comment]
>Otherwise maybe lets just drop the "defaults" and require book.toml to override the "theme"

That might be a good idea! In that case, the `--theme` argument should add the corresponding path to the config in addition to create the theme dir. I'm not sure this is such an easy task however.

**Comment by budziq** [comment]
Yeah, but on the other hand there is a problem with backward compatibility. At the moment rust-cookbook (and possibly other clients) uses latest mdbook from crates.io in their CI to build content on merge and automatically publish.

If we remove the default theme directory handling, content build step will silently produce output different from expected :(. I can easily fix the problem in rust-cookbook but I don't know how many other clients depend on the current behaviour. 

Maybe a warning about depreciation + clear information in changelog would be needed?

**Comment by azerupi** [comment]
Hmmm, but at some point we are going to make a breaking release. In fact, current master is already a breaking some things from the config file. 

Making a breaking release is inevitable and will certainly happen again in the future. So the next best thing that we can do is figure out a way for the users to pin their CI to the latest non breaking version of mdBook until they want to upgrade. I'm going to make a new meta issue for this because it's an important thing to discuss with the relevant parties.
