### ISSUE TITLE
Inline code blocks do not display properly with cookies disabled

### ISSUE THREAD

**Issue by joshlf** [azerupi/mdBook#322]
When viewing [https://doc.rust-lang.org/book/first-edition/documentation.html](https://doc.rust-lang.org/book/first-edition/documentation.html) from Chrome (Mac, "Version 58.0.3029.110 (64-bit)") with cookies disabled but Javascript enabled, inline code blocks do not display properly. Because of this, the expand and play buttons are not visible (and thus, I was not able to test whether they work).

Here's a block from that page as rendered with cookies enabled:
<img width="778" alt="screen shot 2017-06-10 at 8 15 52 pm" src="https://user-images.githubusercontent.com/1046063/27007957-bf50e122-4e19-11e7-8716-94ed17e81ced.png">

And the same block with cookies disabled (but Javascript still enabled as before):
<img width="720" alt="screen shot 2017-06-10 at 8 15 43 pm" src="https://user-images.githubusercontent.com/1046063/27007962-d34cdd48-4e19-11e7-84b1-d8786b62d2b7.png">

**Comment by azerupi** [comment]
Thank you for the bug report! 
I think this is related to #317 where @budziq is working on a solution, so I am going to mark this as a duplicate. But feel free to correct me if you think it is unrelated to that issue.

**Comment by joshlf** [comment]
Looks like you're probably right; cheers!

**Comment by budziq** [comment]
right it looks like chromium disables localstorage in addition to cookies I
have a slightly different  POC for this one (as opposed to safari I can
actualy reproduce this ine ;) ) but it'll needsome cleanup prior to PR

On 11 Jun 2017 19:15, "Joshua Liebow-Feeser" <notifications@github.com>
wrote:

Looks like you're probably right; cheers!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/azerupi/mdBook/issues/322#issuecomment-307643098>, or mute
the thread

**Comment by budziq** [comment]
Hi @joshlf,

Please check with [this build](https://budziq.github.io/mdBook/format/rust.html#hiding-code-lines) this is work in progress ATM.

**Comment by joshlf** [comment]
@budziq That works! The code renders properly and the "play" button works. I will note (although I suspect this is not related to this issue) that if I've already hit the "play" button and then I hit the "copy" button, the output of clicking "play":
> rustc 1.18.0 (03fc9d622 2017-06-06)
> 12

is copied to my clipboard along with the source code. I don't know if that's intentional.

**Comment by budziq** [comment]
yeah I know about that one too . As I am working mostly with rust-cookbook
(where play button is disabled)  I have found it today :( . This is due to
the fact that clipboard gets whole innerhtml from code snippet and
playground overwrites the text with playpen output. most likely we will
need to change clipboard code or split playpen output to separate div.

It would be great If you could open a bug report about the clipboard (it
also pastes one spurious  \n line at the top of code snippet).

On 11 Jun 2017 9:45 p.m., "Joshua Liebow-Feeser" <notifications@github.com>
wrote:

@budziq <https://github.com/budziq> That works! The code renders properly
and the "play" button works. I will note (although I suspect this is not
related to this issue) that if I've already hit the "play" button and then
I hit the "copy" button, the output of clicking "play":

rustc 1.18.0 (03fc9d622 2017-06-06)
12

is copied to my clipboard along with the source code. I don't know if
that's intentional.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/azerupi/mdBook/issues/322#issuecomment-307651911>, or mute
the thread

**Comment by joshlf** [comment]
Sure, I'll open another issue.
