### ISSUE TITLE
Release 0.0.23?

### ISSUE THREAD

**Issue by ffissore** [azerupi/mdBook#379]
The latest tag is 0.0.21 https://github.com/azerupi/mdBook/tags
However on crates.io, version is 0.0.22 https://crates.io/crates/mdbook

Rust book has the navigation bug, fixed in #337, but the fix is not included in latest 0.0.22.

Can you release 0.0.23?

**Comment by budziq** [comment]
Hi @ffissore 

in fact there are a lot of other unreleased bugfixes but there are already several  breaking changes in master as well as we are pushing for 0.1.0 release which will be a major one (most of the work has been [already done](https://github.com/azerupi/mdBook/milestone/6). And due to the breaking changes we are unlikely to release another patch release in the meantime. 

Please bear with us as we are even more eager to finally publish the 0.1.0 goodness 😄

**Comment by agauniyal** [comment]
Waiting for next release as well, any ETA we could get at this point 😄 ?

**Comment by azerupi** [comment]
A new release has been made recently (0.0.25) it's not the 0.1 that we promised because the docs are not up to date yet, but it contains all the changes that were meant for the 0.1 :)

**Comment by agauniyal** [comment]
Thankyou so much @azerupi :)

**Comment by azerupi** [comment]
I don't maintain the AUR package, so I am not sure if it is still maintained and if / when it will update. But I can speak for the releases. We have had some trouble with our CI infrastructure, so the release artefacts where not pushed to GitHub for the last couple of releases. Hopefully this will be fixed for the next release. 

In the mean time, you can install from crates.io using cargo :)
