### ISSUE TITLE
Option to increase the font-size 

### ISSUE THREAD

**Issue by ShalokShalom** [azerupi/mdBook#410]
Gitbook offers the option to increase the font size, which is important for my eyes.

**Comment by steveklabnik** [comment]
Does using the browser to increase the size have problems?

**Comment by opiation** [comment]
Can this be reopened to improve mobile accessibility?  If required, I can open a new issue.

On both Chrome for Mobile and Brave mobile browser (both using Webkit I think), the font size does not seem to be affected by their [**Text scaling** accessibility settings](https://support.google.com/chrome/answer/96810?co=GENIE.Platform%3DAndroid&hl=en) leaving only the pinch zoom option.  While pinch zoom works, it then requires scrolling both vertically and horizontally to read rather than actually changing the font-size which would just reflow the page and require more vertical scaling.  Pinch-zooming in and out constantly to read a mostly textual document can be quite cumbersome or tedious for those with accessibility challenges.
