### ISSUE TITLE
Travis is broken since 1.20 release

### ISSUE THREAD

**Issue by behnam** [azerupi/mdBook#421]
Travis has been broken since the rust 1.20 release. Looks like a problem with `rustup-setup`. (It was recently renamed or something, IIRC.)

History: https://travis-ci.org/azerupi/mdBook/branches
First failure: https://travis-ci.org/azerupi/mdBook/builds/270512490

```
+curl -O https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-setup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8047k  100 8047k    0     0   109M      0 --:--:-- --:--:-- --:--:--  113M
+chmod +x rustup-setup
+./rustup-setup -y
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
error: missing key: 'url'
```

I'm not sure why the normal travis/rust infra is not being used here and the rust/cargo installation is done manually.

**Comment by azerupi** [comment]
The travis infra has been contributed mostly by Japaric two years ago and has been updated approximately one year ago. It has never been touched since. We should completely update our CI infra to the current best practices. 

I opened #387 not long ago to start discussion about this. You are welcome to join the discussion and propose changes. :)

**Comment by azerupi** [comment]
Travis should work again with #429 :)
