### ISSUE TITLE
More breakage: -- in anchors

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#428]
Yet more breakage when trying to use mdbook 0.0.24 on the rust book

A heading like this

    ## `--passes`

used to give `#--passes`, but now gives `passes`

    ## Method-call expressions

used to give `#method-call-expressions` but now gives `#methodcall-expressions`

Were these intentional?

This is semi-important to resolve as Rust's build is now warning due to the errors from back in `0.0.22`, so cleaning those up soon would be great!

**Comment by azerupi** [comment]
I am a little confused. How could `## `--passes`` become `#--passes-add-more-rustdoc-passes` where does the rest come from?

>used to give #method-call-expressions but now gives #methodcall-expressions

The old way seems more sensible. I'm going to take a look, once it is resolved we should definitely  make some tests for this because it seems like a portion that is particularly sensitive to breakage.

**Comment by steveklabnik** [comment]
> How could ##--passes`` become #--passes-add-more-rustdoc-passes where does the rest come from?

Ugh sorry, I mis-copy/pasted; the actual title is

    ## `--passes`: add more rustdoc passes

but since most of that doesn't matter for the purposes of this bug, I removed it. But apparently missed a spot. I will update the original issue.

**Comment by azerupi** [comment]
Commit https://github.com/azerupi/mdBook/commit/84ef4d261769628474c1285bb07a96665c105f80 should solve this. Can you test with master? If there is any other breakage, let me know. Otherwise I will do a 0.0.25 release.

I added your two breakage examples to the tests. It is not much, we should probably add more but at least we have already something.

**Comment by steveklabnik** [comment]
I will test right now 👍

**Comment by steveklabnik** [comment]
> Build completed successfully in 0:04:50

🎊

**Comment by azerupi** [comment]
I will release a new version then! :)

**Comment by azerupi** [comment]
Version 0.0.25 released!

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/44430 ❤️
